/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministradoresRouteImport } from './routes/_authenticated/administradores'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDisciplinasRouteImport } from './routes/_authenticated/disciplinas'
import { Route as AuthenticatedEspecialidadesRouteImport } from './routes/_authenticated/especialidades'
import { Route as AuthenticatedFormadoresRouteImport } from './routes/_authenticated/formadores'
import { Route as AuthenticatedPreLideresRouteImport } from './routes/_authenticated/pre-lideres'
import { Route as AuthenticatedPresencasRouteImport } from './routes/_authenticated/presencas'
import { Route as AuthenticatedRegioesRouteImport } from './routes/_authenticated/regioes'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministradoresRoute =
  AuthenticatedAdministradoresRouteImport.update({
    id: '/administradores',
    path: '/administradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisciplinasRoute =
  AuthenticatedDisciplinasRouteImport.update({
    id: '/disciplinas',
    path: '/disciplinas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspecialidadesRoute =
  AuthenticatedEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormadoresRoute = AuthenticatedFormadoresRouteImport.update({
  id: '/formadores',
  path: '/formadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreLideresRoute = AuthenticatedPreLideresRouteImport.update({
  id: '/pre-lideres',
  path: '/pre-lideres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresencasRoute = AuthenticatedPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegioesRoute = AuthenticatedRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administradores': typeof AuthenticatedAdministradoresRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disciplinas': typeof AuthenticatedDisciplinasRoute
  '/especialidades': typeof AuthenticatedEspecialidadesRoute
  '/formadores': typeof AuthenticatedFormadoresRoute
  '/pre-lideres': typeof AuthenticatedPreLideresRoute
  '/presencas': typeof AuthenticatedPresencasRoute
  '/regioes': typeof AuthenticatedRegioesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administradores': typeof AuthenticatedAdministradoresRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disciplinas': typeof AuthenticatedDisciplinasRoute
  '/especialidades': typeof AuthenticatedEspecialidadesRoute
  '/formadores': typeof AuthenticatedFormadoresRoute
  '/pre-lideres': typeof AuthenticatedPreLideresRoute
  '/presencas': typeof AuthenticatedPresencasRoute
  '/regioes': typeof AuthenticatedRegioesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administradores': typeof AuthenticatedAdministradoresRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disciplinas': typeof AuthenticatedDisciplinasRoute
  '/_authenticated/especialidades': typeof AuthenticatedEspecialidadesRoute
  '/_authenticated/formadores': typeof AuthenticatedFormadoresRoute
  '/_authenticated/pre-lideres': typeof AuthenticatedPreLideresRoute
  '/_authenticated/presencas': typeof AuthenticatedPresencasRoute
  '/_authenticated/regioes': typeof AuthenticatedRegioesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administradores'
    | '/auditoria'
    | '/avaliacoes'
    | '/configuracoes'
    | '/conta'
    | '/dashboard'
    | '/disciplinas'
    | '/especialidades'
    | '/formadores'
    | '/pre-lideres'
    | '/presencas'
    | '/regioes'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administradores'
    | '/auditoria'
    | '/avaliacoes'
    | '/configuracoes'
    | '/conta'
    | '/dashboard'
    | '/disciplinas'
    | '/especialidades'
    | '/formadores'
    | '/pre-lideres'
    | '/presencas'
    | '/regioes'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administradores'
    | '/_authenticated/auditoria'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conta'
    | '/_authenticated/dashboard'
    | '/_authenticated/disciplinas'
    | '/_authenticated/especialidades'
    | '/_authenticated/formadores'
    | '/_authenticated/pre-lideres'
    | '/_authenticated/presencas'
    | '/_authenticated/regioes'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administradores': {
      id: '/_authenticated/administradores'
      path: '/administradores'
      fullPath: '/administradores'
      preLoaderRoute: typeof AuthenticatedAdministradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disciplinas': {
      id: '/_authenticated/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof AuthenticatedDisciplinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/especialidades': {
      id: '/_authenticated/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof AuthenticatedEspecialidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formadores': {
      id: '/_authenticated/formadores'
      path: '/formadores'
      fullPath: '/formadores'
      preLoaderRoute: typeof AuthenticatedFormadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pre-lideres': {
      id: '/_authenticated/pre-lideres'
      path: '/pre-lideres'
      fullPath: '/pre-lideres'
      preLoaderRoute: typeof AuthenticatedPreLideresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presencas': {
      id: '/_authenticated/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof AuthenticatedPresencasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regioes': {
      id: '/_authenticated/regioes'
      path: '/regioes'
      fullPath: '/regioes'
      preLoaderRoute: typeof AuthenticatedRegioesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministradoresRoute: typeof AuthenticatedAdministradoresRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisciplinasRoute: typeof AuthenticatedDisciplinasRoute
  AuthenticatedEspecialidadesRoute: typeof AuthenticatedEspecialidadesRoute
  AuthenticatedFormadoresRoute: typeof AuthenticatedFormadoresRoute
  AuthenticatedPreLideresRoute: typeof AuthenticatedPreLideresRoute
  AuthenticatedPresencasRoute: typeof AuthenticatedPresencasRoute
  AuthenticatedRegioesRoute: typeof AuthenticatedRegioesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministradoresRoute: AuthenticatedAdministradoresRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisciplinasRoute: AuthenticatedDisciplinasRoute,
  AuthenticatedEspecialidadesRoute: AuthenticatedEspecialidadesRoute,
  AuthenticatedFormadoresRoute: AuthenticatedFormadoresRoute,
  AuthenticatedPreLideresRoute: AuthenticatedPreLideresRoute,
  AuthenticatedPresencasRoute: AuthenticatedPresencasRoute,
  AuthenticatedRegioesRoute: AuthenticatedRegioesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
